# Generated by Django 5.0.4 on 2024-04-12 16:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('biografia', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ct', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=999999999)),
                ('avatar', models.URLField(max_length=100, null=True)),
                ('posts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seguidores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seguidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cuenta_privada', models.BooleanField(default=False)),
                ('notificaciones', models.BooleanField(default=True)),
                ('sms_code', models.IntegerField(default=999999, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to='hackapp_app.usuario')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to='hackapp_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo_publicacion', models.IntegerField(choices=[(0, 'Noticia'), (1, 'Exploit'), (2, 'Foro')], default=0)),
                ('link_externo', models.URLField(max_length=100, null=True)),
                ('imagen', models.URLField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('gravedad', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Critical')], default=0, null=True)),
                ('cve', models.CharField(max_length=13, null=True, unique=True)),
                ('probado', models.CharField(max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('valoracion', models.FloatField(default=0)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp_app.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp_app.usuario')),
            ],
        ),
    ]
