# Generated by Django 5.0.4 on 2024-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='gravedad',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.IntegerField(choices=[(1, 'Noticia'), (2, 'Exploit'), (3, 'Foro')], default=0),
        ),
    ]
