# Generated by Django 5.0.4 on 2024-04-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp_app', '0002_alter_publicacion_gravedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='valoracion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp_app.comentario')),
            ],
        ),
    ]
