# Generated by Django 5.0.4 on 2024-05-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp_app', '0005_alter_usuario_sms_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sms_code',
        ),
    ]
